#!/bin/bash
# Post installation script
# ------------------------
# First run

createFlag() {
    mkdir -p "/home/$USER/.config/crunchbang"
    touch "/home/$USER/.config/crunchbang/cb-welcome"
}

runInTerminal() {
    if [[ -x /usr/bin/terminator ]]; then
        terminator --title='#! Post-installation Script' --command='cb-welcome'
        exit 0
#    else # Fallback to xterm?
#        xterm -T '#! Post-installation Script' -e 'cb-welcome'
    fi
}

if [[ $1 = '--firstrun' ]]; then
    if [[ -d /live/overlay || -e /home/$USER/.config/crunchbang/cb-welcome ]]; then
        exit 0
    fi
    
    if ! [[ $(groups) =~ ( |^)sudo( |$) ]]; then
        createFlag
        exit 0
    fi
    
    runInTerminal
fi

# Open in terminator
if [[ $1 = '--open' ]]; then
    runInTerminal
fi

createFlag

if ! [[ $(groups) =~ ( |^)sudo( |$) ]]; then
  echo 'Error: must be a member of the sudo group to run this script.' # TODO 'root' user is not a member of the sudo group. Is it meant to restrict root from executing this script?
  exit 1
fi

LIBDIR='/home/alex/git/cb-welcome/lib-cb-welcome' #'/usr/lib/lib-cb-welcome'

# Importing variables and functions from cb-include.cfg
if [[ -f /usr/bin/cb-include.cfg ]]; then
    source '/usr/bin/cb-include.cfg'
else
    echo 'Error: Failed to locate cb-include.cfg'
    exit 1
fi

# Import prompt
if [[ -f ${LIBDIR}/prompt ]]; then
	source "${LIBDIR}/prompt"
else
	echo 'Error: Failed to locate prompt'
	exit 1
fi

# Run through steps
STEPS_BASIC=('apt-update' 'apt-dist-upgrade' 'install-printer-packages' 'install-java-packages' 'install-libreoffice' 'devel')
STEPS_DEVEL=('devel-install-version-control-tools' 'devel-install-ssh-server' 'devel-install-lamp-stack' 'devel-install-packaging-tools')
STEP=1
(( STEPS = ${#STEPS_BASIC[@]} + ${#STEPS_DEVEL[@]} + 2 )) # 2 is intro and fini

. "$LIBDIR/intro"
connectiontest

for curStep in "${STEPS_BASIC[@]}"; do
    ((STEP++))
    . "$LIBDIR/$curStep"
done

if [[ $DEVEL ]]; then
    for curStep in "${STEPS_DEVEL[@]}"; do
        ((STEP++))
        . "$LIBDIR/$curStep"
    done
fi

. "$LIBDIR/fini"

exit 0
